services:
  server:
    build: .
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/todo_db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: postgres:12.19-bullseye
    container_name: db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s